$lock_cmd = hyprctl dispatch 'hl.dsp.global("proscenio:lock")' & pidof proscenio hyprlock || hyprlock
# $lock_cmd = pidof hyprlock || hyprlock
$suspend_cmd = systemctl suspend || loginctl suspend

general {
    lock_cmd = $lock_cmd
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.global("proscenio:lockFocus")'
    inhibit_sleep = 3
}

listener {
    timeout = 1800 # 30mins
    on-timeout = loginctl lock-session
}

listener {
    timeout = 2100 # 35mins
    on-timeout = $suspend_cmd
}
